apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver5
  labels:
    app: goserver5
spec:
  selector:
    matchLabels:
      app: goserver5
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver5"
    spec:
      containers:
        - name: goserver5
          image: "vieira900/vieira900:v5.3"
          envFrom:
            - configMapRef:
                name: goserver-env
          volumeMounts:
            - mountPath: "go/myfamily"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
            - key: members
              path: "family.txt"