apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver5 
  labels:
    app: goserver5
spec:
  selector:
    matchLabels:
      app: goserver5
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver5"
    spec:
      containers:
        - name: goserver5
          image: "vieira900/vieira900:v4"
          envFrom:
            - configMapRef:
                name: goserver-env
#          env:
#            - name: NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env
#                  key: NAME
#            - name: AGE
#              valueFrom:
#                configMapKeyRef:
#                  name: goserver-env
#                  key: Age
